spring:
  kafka:
    producer:
      bootstrap-servers: ["kafka-svc:9092"]
  cloud:
    inetutils:
      default-hostname: yamp-backend.local

  config:
    activate:
      on-profile: local-dev
  datasource:
    username: dev
    url: jdbc:postgresql://localhost:5432/user-svc-db
    driver-class-name: org.postgresql.Driver
    password: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
logging:
  level:
    org.apache.tomcat: DEBUG
    org.springframework.web: DEBUG
    com.example.userservice.controller: DEBUG
    com.example.userservice.service: DEBUG
    com.example.yamp.usersvc.event: DEBUG
  pattern:
    level:  "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"