name: user-svc-dev
services:
  user-svc:
    image: ghcr.io/ngodat0103/nt548/user-svc:${TAG:-dev-latest}
    build:
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: user-svc
        VERSION: ${TAG:-dev-latest}
        SERVICE_PORT: 8002
    environment:
      - SPRING_PROFILES_ACTIVE=local-dev
networks:
  yamp-network:
    name: yamp-dev
    external: true