AWSTemplateFormatVersion: '2010-09-09'
Description: 'Network stack'
Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: '10.0.0.0/16'
      EnableDnsHostnames: 'true'
      Tags:
      - Key: Lab01
        Value: 'VPC'
  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties: {}
  VPCGatewayAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
  SubnetPublic:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: '10.0.1.0/24'
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC
      Tags:
      - Key: Lab01
        Value: 'Public Proxy'
  SubnetPrivate:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: '10.0.2.0/24'
      VpcId: !Ref VPC
      Tags:
      - Key: Lab01
        Value: 'Private Subnet'


Outputs:
  SubnetPublicProxyExport:
    Value: !Ref SubnetPublic
    Description: 'Public proxy subnet'
    Export:
      Name: SubnetPublicProxyExport
  SubnetPrivateExport:
    Value: !Ref SubnetPrivate
    Description: 'Private backend subnet'
    Export:
      Name: SubnetPrivateExport

