services:
  auth-svc-db:
    profiles: ['dev','all']
    image: "bitnami/postgresql:16.4.0-debian-12-r23"
    entrypoint:
      - sh
      - -euc
      - |
        cat <<EOF > /docker-entrypoint-initdb.d/init-dev-user.sql
        create role "dev" with password 'dev' ; 
        create database "auth-svc-db" with owner  "dev";
        grant connect to "auth-svc-user";
        alter role "dev" with login; 
        EOF
        /opt/bitnami/scripts/postgresql/entrypoint.sh /opt/bitnami/scripts/postgresql/run.sh
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  zookeeper:
    profiles: ['dev','all']
    volumes:
      - var-lib-zookeeper-data:/var/lib/zookeeper/data
      - var-lib-zookeeper-log:/var/lib/zookeeper/log
    networks:
      - yamp-network
    image: confluentinc/cp-zookeeper:7.4.6
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181"
  kafka-svc:
    restart: unless-stopped
    profiles: ['dev','all']
    networks:
     - yamp-network
    image: confluentinc/cp-kafka:7.4.6
    depends_on:
      zookeeper:
        condition: service_started
    ports:
      - "9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-svc:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  auth-svc:
    profiles: ['all']
    container_name: auth-svc
    image: ghcr.io/ngodat0103/nt548/auth-svc:${TAG:-dev-latest}
    healthcheck:
      test: ['CMD','curl','http://127.0.0.1:8001/api/v1/auth/actuator/health/liveness']
      interval: 10s
      retries: 5


    build:
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: auth-svc
        VERSION: ${TAG:-dev-latest}
        SERVICE_PORT: 8001
    depends_on:
      auth-svc-db:
        condition: service_started
      kafka-svc:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=local-dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-svc-db:5432/auth-svc-db
      - SPRING_DATASOURCE_USERNAME=dev
      - SPRING_DATASOURCE_PASSWORD=dev
volumes:
  var-lib-zookeeper-data:
    external: true
  var-lib-zookeeper-log:
    external: true
  postgres-data:
networks:
  yamp-network:
    name: yamp-dev
    external: true