{{if .Values.secretStores.vault }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "user-svc.fullname" . }}-external-secret
  labels:
    {{- include "user-svc.labels" . | nindent 4 }}
spec:
  refreshInterval: "10s"
  secretStoreRef:
    name: {{ include "user-svc.fullname" . }}-secret-store
    kind: SecretStore
  target:
    name: {{.Values.secretRef.name}}
  data:
    - secretKey: MONGODB_ROOT_PASSWORD
      remoteRef:
        key: se347/backend/dev/user-svc
        property: MONGODB_ROOT_PASSWORD
    - secretKey: MONGODB_USERNAME
      remoteRef:
        key: se347/backend/dev/user-svc
        property: MONGODB_USERNAME
    - secretKey: MONGODB_PASSWORD
      remoteRef:
        key: se347/backend/dev/user-svc
        property: MONGODB_PASSWORD
{{- end }}