apiVersion: v2
name: user-svc
description: A Helm chart for user-svc

type: application

version: 0.0.1
appVersion: "0.0.1"

dependencies:
  - name: postgresql
    version: 16.0.1
    repository: https://charts.bitnami.com/bitnami