name: user-svc webhook
on:
  workflow_dispatch:
  push:
    branches:
      - "dev"
    paths:
      - "lab02/app/user-svc/src/main/**"
      - "lab02/app/user-svc/Dockerfile"
 
jobs:   
  send-webhook:
    name: Send webhook to Jenkins
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook to Jenkins
        uses: distributhor/workflow-webhook@v3.0.7
        with:
          webhook_url: ${{ secrets.WEBHOOK_ENDPOINT }}
          webhook_auth_type: 'bearer'
          webhook_type: 'json'
          webhook_auth: ${{ secrets.WEBHOOK_USER_SVC_TOKEN }}